server:
   port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: http://localhost:8081/
        predicates:
        - Path=/v1/**
      - id: studentModule
        uri: http://localhost:8082/
        predicates:
        - Path=/v2/**
